INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_BLOCKSTREAM blockstream)

FIND_PATH(
    BLOCKSTREAM_INCLUDE_DIRS
    NAMES blockstream/api.h
    HINTS $ENV{BLOCKSTREAM_DIR}/include
        ${PC_BLOCKSTREAM_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    BLOCKSTREAM_LIBRARIES
    NAMES gnuradio-blockstream
    HINTS $ENV{BLOCKSTREAM_DIR}/lib
        ${PC_BLOCKSTREAM_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BLOCKSTREAM DEFAULT_MSG BLOCKSTREAM_LIBRARIES BLOCKSTREAM_INCLUDE_DIRS)
MARK_AS_ADVANCED(BLOCKSTREAM_LIBRARIES BLOCKSTREAM_INCLUDE_DIRS)

